export { difference } from './functions/difference.function';
export { disjoint } from './functions/disjoint.function';
export { equivalence } from './functions/equivalence.function';
export { intersection } from './functions/intersection.function';
export { sort } from './functions/sort.function';
export { subset } from './functions/subset.function';
export { superset } from './functions/superset.function';
export { union } from './functions/union.function';
export { xor } from './functions/xor.function';
